include classpath("application.conf")

node-address {
    protocol = http
    host = localhost
    port = 9324
    context-path = ""
}

rest-sqs {
    enabled = true
    bind-port = 9324
    bind-hostname = "0.0.0.0"
}

queues {
    "docintel-local-ingest" {}

    "docintel-local-ocr.fifo" {
        fifo = true
        contentBasedDeduplication = false
    }

    "docintel-local-structure.fifo" {
        fifo = true
        contentBasedDeduplication = false
    }

    "docintel-local-match.fifo" {
        fifo = true
        contentBasedDeduplication = false
    }

    "docintel-local-persist.fifo" {
        fifo = true
        contentBasedDeduplication = false
    }

    "docintel-local-index.fifo" {
        fifo = true
        contentBasedDeduplication = false
    }
}
